Feat/#9 상품 crud 기본 뼈대 로직
Palgona/Backend pull request #13
Opened 2024-02-08 09:58 UTC by JangWooJin1

## 개요

- 상품 crud 기본 뼈대 로직 작성

## 작업사항

- 상품 등록 API 구현
- 상품 조회 API 구현
- 상품 수정 API 구현
- 상품 삭제 API 구현

2024-02-09 12:19 UTC, jinsu868 commented on src/main/java/com/palgona/palgona/controller/ProductController.java
> +public class ProductController {
저희 api 명세서 작성할 때 url prefix로 /api/v1/ 붙이기로 했어서 추가해주시면 될 것 같아요:)

2024-02-09 12:19 UTC, jinsu868 commented on src/main/java/com/palgona/palgona/controller/ProductController.java
> +            value = "/product",
rest api 컨벤션에 명사는 복수가 기본이라 /products 로 잡아주면 좋을 것 같아요!

2024-02-09 12:19 UTC, jinsu868 commented on src/main/java/com/palgona/palgona/controller/ProductController.java
> +    public ResponseEntity<ProductResponse> readProduct( @PathVariable Long id ){
`( @PathVariable Long id )` 양쪽에 공백 제거해주시면 좋을 것 같습니다:)

2024-02-09 12:19 UTC, jinsu868 commented on src/main/java/com/palgona/palgona/domain/image/Image.java
> +    @ManyToOne(targetEntity = Member.class)
`targetEntity = Member.class`랑  `foreignKey = @ForeignKey(name = "fk_image_to_member")` 는 처음보는 세팅인데 어떤 기능을 하는 건가요?
그리고 Member는 프로필 이미지 하나만 가져서 연관관계 없이 S3에 저장하고 imageUrl만 필드로 가지게 해둬서 이부분은 없어야 될 것 같아요!

2024-02-09 12:19 UTC, jinsu868 commented on src/main/java/com/palgona/palgona/domain/product/Product.java
> +    @ManyToOne(targetEntity = Member.class)
@XToOne 관계가 기본값이 EAGER 라서 지연로딩 세팅 해주시면 좋을 것 같습니다!

2024-02-09 12:19 UTC, jinsu868 commented on src/main/java/com/palgona/palgona/domain/product/Product.java
> +    public void updateName(String name){
name, initialPrice, content, category, deadline 이 update에서 한번에 수정되니까 하나의 값(embedded)으로 취급하는 게 좋을 것 같아요:)

2024-02-09 12:19 UTC, jinsu868 commented on src/main/java/com/palgona/palgona/domain/product/ProductImage.java
> +@Table(name = "product_image", uniqueConstraints = {
저는 이 부분은 없어도 될 것 같은데 어떻게 생각하시나요?

2024-02-09 12:19 UTC, jinsu868 commented on src/main/java/com/palgona/palgona/domain/product/ProductImage.java
> +    @ManyToOne(targetEntity = Image.class)
ProductImage - Image 는 OneToOne 아닌가요?

2024-02-09 12:19 UTC, jinsu868 commented on src/main/java/com/palgona/palgona/service/ProductService.java
> +        Product product = productRepository.findById(productId).get();
Optional 에서 get() 으로 값을 가져오는 건 지양되는 걸로 알고 있어요!
```java
Product product = productRepository.findById(productId)
  .orElseThrow(() -> new CustomException());
```

2024-02-11 03:15 UTC, janghoosa requested changes
답변 남겨주신것은 수정 안하고 머지시킬까요?

2024-02-12 10:23 UTC, merged

2024-02-14 15:05 UTC, JangWooJin1 commented on src/main/java/com/palgona/palgona/controller/ProductController.java
> +public class ProductController {
넵!

2024-02-14 15:05 UTC, JangWooJin1 commented on src/main/java/com/palgona/palgona/controller/ProductController.java
> +            value = "/product",
넵!

2024-02-14 15:06 UTC, JangWooJin1 commented on src/main/java/com/palgona/palgona/controller/ProductController.java
> +    public ResponseEntity<ProductResponse> readProduct( @PathVariable Long id ){
넵!

2024-02-14 15:15 UTC, JangWooJin1 commented on src/main/java/com/palgona/palgona/domain/image/Image.java
> +    @ManyToOne(targetEntity = Member.class)
1. targetEntity 설정은 제가 그동안 배운 내용을 바탕으로 적용한건데, 찾아보니 굳이 없어도 되는 기능이네요. 해당 부분 제거하겠습니다!
2. foreignKey = @ForeignKey(name = "fk_image_to_member")는 외래키 제약 조건에 이름을 부여하는 속성입니다. 나중에 오류가 발생했을 때, 어디서 문제가 생겼는지 쉽게 추적할 수 있도록 하려고 추가한 세팅인데 굳이 없어도 될거같아요!
3. image의 외래키(fk)는 ERD에서 누가 해당 이미지를 업로드했는지 확인하기 위해 추가한 컬럼이라고 알고 있어서 추가하였습니다!

2024-02-14 15:17 UTC, JangWooJin1 commented on src/main/java/com/palgona/palgona/domain/product/Product.java
> +    @ManyToOne(targetEntity = Member.class)
넵!

2024-02-14 15:20 UTC, JangWooJin1 commented on src/main/java/com/palgona/palgona/domain/product/ProductImage.java
> +    @ManyToOne(targetEntity = Image.class)
아 제가 실수했네요 수정하겠습니다!

2024-02-14 15:20 UTC, JangWooJin1 commented on src/main/java/com/palgona/palgona/domain/product/Product.java
> +    public void updateName(String name){
넵!

2024-02-14 15:20 UTC, JangWooJin1 commented on src/main/java/com/palgona/palgona/service/ProductService.java
> +        Product product = productRepository.findById(productId).get();
넵!

2024-02-14 16:00 UTC, jinsu868 commented on src/main/java/com/palgona/palgona/domain/image/Image.java
> +    @ManyToOne(targetEntity = Member.class)
> image의 외래키(fk)는 ERD에서 누가 해당 이미지를 업로드했는지 확인하기 위해 추가한 컬럼이라고 알고 있어서 추가하였습니다!

제가 Member 프로필 이미지 넣을 때 프로필 사진은 하나로 고정이라서 연관관계없이 이미지 Url만 저장하게 해둬서 말씀드렸던 거예요!
고생하셨습니다👍