Feat/#22 상품 찜 추가 및 삭제 로직 추가
Palgona/Backend pull request #27
Opened 2024-02-17 10:11 UTC by JangWooJin1

## 개요

- 상품 찜 추가 및 삭제 로직 추가

## 작업대상

#22 

## 변경로직

- Bookmark 엔티티 추가
- BookmarkRepository 추가
- BookmarkService 추가
- BookmarkController 추가

2024-02-19 06:39 UTC, janghoosa requested changes
수고하셨습니다~~

2024-02-19 06:39 UTC, janghoosa commented on src/main/java/com/palgona/palgona/service/BookmarkService.java
> +        bookmarkRepository.deleteByMemberAndProductId(member, productId);
그때 말씀드렸던 것처럼 member와 product를 가져와서 bookmark를 찾는것으로 바꿔주시면 머지 시킬게요!

2024-02-19 09:37 UTC, JangWooJin1 commented on src/main/java/com/palgona/palgona/service/BookmarkService.java
> +        bookmarkRepository.deleteByMemberAndProductId(member, productId);
넵!

2024-02-20 03:36 UTC, janghoosa commented on src/main/java/com/palgona/palgona/service/BookmarkService.java
> +                .orElseThrow(() -> new IllegalArgumentException());
비즈니스 익셉션으로 바꿔주실 수 있으실까요?

2024-02-20 08:46 UTC, JangWooJin1 commented on src/main/java/com/palgona/palgona/service/BookmarkService.java
> +                .orElseThrow(() -> new IllegalArgumentException());
넵!

2024-02-20 10:25 UTC, jinsu868 approved these changes
수고하셨습니다!

2024-02-23 05:26 UTC, janghoosa approved these changes

2024-02-23 05:26 UTC, merged