Feat/#31 맴버 조회 API 페이징 처리
Palgona/Backend pull request #32
Opened 2024-02-18 17:52 UTC by jinsu868

## 개요

- #31 

## 작업사항

- Querydsl 설정
- 맴버 조회 페이징 방식 변경

## 변경로직

- 맴버 조회 로직 변경

2024-02-19 06:25 UTC, janghoosa reviewed
빠르시네요! 수고하셨습니다.

2024-02-19 06:25 UTC, janghoosa commented on src/main/java/com/palgona/palgona/repository/member/MemberRepositoryImpl.java
> +    }
dto로 매핑하는건 controller단에서 해야하지 않을까요?
slice로 받아와서 controller에서 매핑해야 책임이 확실히 분리될 것 같아요.

2024-02-19 09:36 UTC, JangWooJin1 requested changes
고생하셨습니다!

2024-02-19 09:36 UTC, JangWooJin1 commented on src/main/java/com/palgona/palgona/service/MemberService.java
> +        validateAdmin(adminMember.getMember());
해당 api는 관리자만 들어갈 수 있으니까, service단에서 처리하기보다는 시큐리티 설정에서 hasRole()로 처리하는 방법은 어떤가요?

2024-02-19 14:41 UTC, jinsu868 commented on src/main/java/com/palgona/palgona/repository/member/MemberRepositoryImpl.java
> +    }
db에서 조회할 때 Projection으로 조회해서 dto 변환 로직은 따로 없는데 혹시 List -> Slice 로 변환하는 부분 말씀하시는 걸까요?

2024-02-19 14:41 UTC, jinsu868 commented on src/main/java/com/palgona/palgona/service/MemberService.java
> +        validateAdmin(adminMember.getMember());
좋습니다.
#29 
해당 이슈 처리할 때 수정해서 같이 올릴게요!

2024-02-20 05:26 UTC, janghoosa approved these changes

2024-02-20 05:26 UTC, janghoosa commented on src/main/java/com/palgona/palgona/repository/member/MemberRepositoryImpl.java
> +    }
네 맞아요. 근데 제가 잘못 봤네요.
response라고 되어있어서 dto인줄 알았는데 hasNext랑 nextCursor를 알려주기 위해 이런 방식을 쓰신거군요.
좋은 코드인거 같아요.

2024-02-20 08:42 UTC, JangWooJin1 approved these changes

2024-02-20 08:42 UTC, merged